version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-docker
    container_name: laravel-app
    restart: always
    ports:
      - 7070:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - mailhog
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel_docker
      DB_USERNAME: app
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  mailhog:
    image: mailhog/mailhog
    container_name: laravel-mailcatcher
    restart: always
    user: root
    ports:
      - 1025:1025
      - 8025:8025
